INU-BJJ/bjj-iOS

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BackButton.imageset/BackButton.svg
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BackButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/XButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/XButton.imageset/XButton.svg
- BJJ_iOS/BJJ_iOS/Source/Extensions/UINavigationItem++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/ViewController/MenuReviewViewController.swift
> [Feat] 네비게이션바 구현

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/Model/MenuItem.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuHeader/MenuHeader.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewList/MenuReviewImageCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewList/MenuReviewListContent.swift
- #13 
- 하트 아이콘 그림자 효과 구현
- 사진 여러장일 경우 분할되도록 구현
https://github.com/user-attachments/assets/2878fa4d-f82e-4416-b624-e98e4d565e25
> [New Feature] 리뷰 페이지 UI 및 기능 구현

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/ViewController/MenuReviewViewController.swift
- #15 
- 페이지 스크롤 시 네비바 숨김 기능 구현
- 페이지 스크롤 방식 변경 (collectionView -> scrollView)
https://github.com/user-attachments/assets/ce06ebea-4c3a-45f2-bea1-be7e673cdd35
> [UI] 리뷰 페이지 스크롤 방식 변경

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Home/Star.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/FloatingButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/FloatingButton.imageset/FloatingButton.svg
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIButton++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/Model/MyReviewModel.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewFooterView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewHeaderView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/ViewController/MyReviewViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/TabBarController.swift
- #26 
- 리뷰 페이지를 tableView로 구현
- 플로팅 버튼 구현
- 리뷰 페이지 네비바 구현
> [UI] 리뷰탭 마이 리뷰 페이지 UI 구현

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/FloatingButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Review/FloatingButton.imageset/FloatingButton.svg
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIButton++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/Model/MyReviewModel.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewFooterView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/View/MyReviewHeaderView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/ViewController/MyReviewViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/TabBarController.swift
- #25 
- 리뷰 탭의 마이 리뷰 페이지의 UI 구현
> [UI] 리뷰 탭 마이 페이지 UI 구현

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BackButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BlackBackButton.imageset/BlackBackButton.svg
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BlackBackButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/CafeteriaMyReview/View/CafeteriaMyReviewCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/CafeteriaMyReview/ViewController/CafeteriaMyReviewViewController.swift
> [UI] 식당별 마이 리뷰 UI 구현

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BackButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BlackBackButton.imageset/BlackBackButton.svg
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/NavigationBar/BlackBackButton.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/CafeteriaMyReview/View/CafeteriaMyReviewCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/CafeteriaMyReview/ViewController/CafeteriaMyReviewViewController.swift
- #30 
- 식당별 마이 리뷰 페이지의 UI 구현 작업
> [UI] 식당별 마이 리뷰 페이지

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewList/MenuReviewList.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewList/MenuReviewListContent.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/ViewController/MenuDetailViewController.swift
- #56 
- 첫 번째 리뷰만 나오는 버그 수정
- 리뷰 사이의 알수없는 간격이 생기는 버그 수정
https://github.com/user-attachments/assets/4d9e173f-c60d-4fba-adef-fe4cc30cf098
> [Bug] [UI] [Fix] MenuDetail

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Source/Application/SceneDelegate.swift
- BJJ_iOS/BJJ_iOS/Source/Manager/KeychainManager.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Member/MemberAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Member/MemberAddress.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Member/Model/MemberModel.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/SignUp/Model/SignUpModel.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/SignUp/SignUpAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/SignUp/SignUpAddress.swift
- BJJ_iOS/BJJ_iOS/Source/Network/ServiceAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Start/Login/ViewController/LoginViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Start/SignUp/ViewController/SignUpViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/MyPage/ViewController/MyPageViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/TabBarController.swift
> [NewFeature] 로그인 페이지 네트워킹 구현

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
- #74 
- 식당 섹션 trailing값 수정
https://github.com/user-attachments/assets/36f65c19-62c4-4ff8-8725-4222ba689d38
> [UI] 메인 페이지 식당 섹션 trailing값 수정

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Ranking/MenuRanking/View/MenuTopRankingCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewCategorySelect/ReviewCategorySelect.swift
- #76 
- 랭킹 페이지의 개별 메뉴 평점view에 대한 UI 디자인 수정
> [UI] 랭킹 페이지 평점 view UI 변경

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Ranking/MenuRanking/View/MenuRankingCell.swift
- #76 
- Top3 메뉴 평점 외의 순위 평점view의 UI 수정
> [UI] 랭킹 페이지 평점view UI 수정

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Source/Extensions/UIViewController++Extensions.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Review/MyReviewDetail/Model/MyReviewDetailModel.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Review/MyReviewDetail/MyReviewDetailAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Review/MyReviewDetail/MyReviewDetailAddress.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/ViewController/MenuDetailViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/CafeteriaMyReview/ViewController/CafeteriaMyReviewViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/ViewController/MyReviewViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReviewDetail/Model/MyReviewDetailModel.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReviewDetail/Model/MyReviewDetailSection.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReviewDetail/View/MyReviewDetailView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReviewDetail/ViewController/MyReviewDetailViewController.swift
- #82 
- 내가 작성한 리뷰 페이지의 해시태그 색상을 임시로 통일함
> [New Feature] 나의리뷰 상세페이지 해시태그 색상

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReview/ViewController/MyReviewViewController.swift
- #83 
- 마이 리뷰를 ordered dictionary로 저장
> [Bug] 마이 리뷰 식당 순서 버그

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
- #94 
- 식당 버튼 클릭 시 collectionView reloadItems -> 수동 configureCell 함수로 UI 업데이트 방식 변경
- 옆의 식당 버튼 누를 경우 자동으로 식당 섹션 스크롤 되도록 구현
https://github.com/user-attachments/assets/54ca2414-00a7-4d54-a011-2f5283e915c6
> [Bug] 홈 페이지 식당 섹션 선택 UI 버그

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Ranking/MenuRanking/ViewController/MenuRankingViewController.swift
> [New Feature] 메뉴 랭킹 업데이트 날짜 기능

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewListCell/MenuReviewListCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/MyReviewDetail/View/MyReviewDetailView.swift
- #102 
- collectionView 셀 이미지 수정
- 1장
- 2장
- 3장
https://github.com/user-attachments/assets/878eb59d-165d-4c5e-a3ce-4ef523c2ecd5
- 4장
https://github.com/user-attachments/assets/dd304be3-29a9-4e89-8bcb-f8c4966c8d22
> [UI] [Fix] 나의 리뷰 상세 페이지 리뷰 이미지 셀 크기 수정

- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/MenuDetail/View/MenuReviewListCell/MenuReviewListCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewAddPhoto/ReviewAddPhoto.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewAddPhoto/ReviewAddPhotoCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewCategorySelect/ReviewCategorySelect.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewContent/ReviewContentCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/View/ReviewGuidelines/ReviewGuidelines.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Review/ReviewWrite/ViewController/ReviewWriteViewController.swift
- #107 
- 리뷰 사진 크기, 간격 수정
- 리뷰 글자수 0일땐 회색, 1부터 검정색
- 리뷰 작성 유의사항과 리뷰 사진들의 간격 수정
- 리뷰 작성 유의사항 드롭다운 아이콘 위치 수정
- 식당, 메뉴 선택 버튼 드롭다운 아이콘 위치 수정
- 사진 선택 해제 아이콘 위치 수정
https://github.com/user-attachments/assets/eb78c178-556b-4231-83c4-fe0195c1f838
> [Fix] 리뷰 작성 페이지 UI 수정

- BJJ_iOS/BJJ_iOS.xcodeproj/project.pbxproj
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Home/CafeteriaInfoDownArrow.imageset/CafeteriaInfoDownArrow.svg
- BJJ_iOS/BJJ_iOS/Resource/Assets.xcassets/Home/CafeteriaInfoDownArrow.imageset/Contents.json
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/View/HomeCafeteriaInfoView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
- #90 
- 메뉴 섹션과 식당 정보 섹션을 구분하는 구분선 구현
- 식당 정보를 표시하는 label 구현
- 식당 지도 imageView 구현
https://github.com/user-attachments/assets/1f0318f7-6ca3-460e-b279-8c3854736ad5
> [UI] 홈 페이지 식당 정보

- BJJ_iOS/BJJ_iOS/Source/Network/API/Home/Home/HomeAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Home/Home/HomeAddress.swift
- BJJ_iOS/BJJ_iOS/Source/Network/API/Home/Home/Model/HomeModel.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/Model/HomeSection.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/View/HomeCafeteriaInfoCell.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/View/HomeCafeteriaInfoView.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/Home/Home/ViewController/HomeViewController.swift
- #153 
- 식당별 운영 시간, 정보 조회 fetch 함수 구현
https://github.com/user-attachments/assets/feec1e8f-e227-4a4b-8df1-b53560c19028
> [Networking] 홈페이지 식당별 정보 조회 API 연동

- BJJ_iOS/BJJ_iOS/Source/Network/ServiceAPI.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/MyPage/NicknameEdit/ViewController/NicknameEditViewController.swift
- BJJ_iOS/BJJ_iOS/Source/Presentation/Tab/MyPage/Setting/ViewController/SettingViewController.swift
- #149 
- 설정 페이지 레이아웃 수정
- 설정 페이지 UI 수정
> [UI] 설정 페이지 UI 수정
